import LocalizedStrings from 'react-localization';
 
let strings = new LocalizedStrings({
 en:{
   slamBoard:"SLAM BOARD",
   username:"Username",
   timeStamp:"Timestamp",
   bet:"Bet",
   allBets:"All Bets",
   myBets:"My Bets",
   slamMining:"SLAM MINING:",
   rollUnder:"Roll Under",
   lucky:"Lucky",
   betEOS:"Bet EOS",
   betSlam:"Bet SLAM",
   betBetDice:"Bet BETDICE",
   exchanges:"Exchanges",
   instructions:"Instructions",
   twitter:"Twitter",
   telegram:"Telegram",
   web:"Web",
   luckyNumber:"Lucky Number",
   rollUnderToWin:"Roll Under To Win",
   payout:"Payout",
   max:"Max",
   payoutMultipier:"Payout Multiplier",
   winChance:"Win Chance",
   claim:"Claim",
   login:"Login",
   logout:"Logout"

 },
 zh: {
   slamBoard:"SLAM BOARD",
   username:"Username",
   timeStamp:"Timestamp",
   bet:"Bet",
   allBets:"All Bets",
   myBets:"My Bets",
   slamMining:"SLAM MINING:",
   rollUnder:"Roll Under",
   lucky:"Lucky",
   betEOS:"Bet EOS",
   betSlam:"Bet SLAM",
   betBetDice:"Bet BETDICE",
   exchanges:"Exchanges",
   instructions:"Instructions",
   twitter:"Twitter",
   telegram:"Telegram",
   web:"Web",
   luckyNumber:"Lucky Number",
   rollUnderToWin:"Roll Under To Win",
   payout:"Payout",
   max:"Max",
   payoutMultipier:"Payout Multiplier",
   winChance:"Win Chance",
   claim:"Claim",
   login:"Login",
   logout:"Logout"
 },
 jp: {
   slamBoard:"SLAM BOARD",
   username:"Username",
   timeStamp:"Timestamp",
   bet:"Bet",
   allBets:"All Bets",
   myBets:"My Bets",
   slamMining:"SLAM MINING:",
   rollUnder:"Roll Under",
   lucky:"Lucky",
   betEOS:"Bet EOS",
   betSlam:"Bet SLAM",
   betBetDice:"Bet BETDICE",
   exchanges:"Exchanges",
   instructions:"Instructions",
   twitter:"Twitter",
   telegram:"Telegram",
   web:"Web",
   luckyNumber:"Lucky Number",
   rollUnderToWin:"Roll Under To Win",
   payout:"Payout",
   max:"Max",
   payoutMultipier:"Payout Multiplier",
   winChance:"Win Chance",
   claim:"Claim",
   login:"Login",
   logout:"Logout"
 },
 ko: {
   slamBoard:"SLAM BOARD",
   username:"Username",
   timeStamp:"Timestamp",
   bet:"Bet",
   allBets:"All Bets",
   myBets:"My Bets",
   slamMining:"SLAM MINING:",
   rollUnder:"Roll Under",
   lucky:"Lucky",
   betEOS:"Bet EOS",
   betSlam:"Bet SLAM",
   betBetDice:"Bet BETDICE",
   exchanges:"Exchanges",
   instructions:"Instructions",
   twitter:"Twitter",
   telegram:"Telegram",
   web:"Web",
   luckyNumber:"Lucky Number",
   rollUnderToWin:"Roll Under To Win",
   payout:"Payout",
   max:"Max",
   payoutMultipier:"Payout Multiplier",
   winChance:"Win Chance",
   claim:"Claim",
   login:"Login",
   logout:"Logout"
 }
});